### ISSUE TITLE
Please support PHP 8

### ISSUE THREAD

**Issue by knivey** [wouterj/peg#2]
Had trouble installing this while using php8

  Could not find package wouterj/peg in any version matching your PHP version, PHP extensions and Composer version:  
    - wouterj/peg dev-master requires php ^7.0 which does not match your installed version 8.0.9.

**Comment by wouterj** [comment]
Hi @knivey! Are you willing to create a PR doing that?

As you might see in the activity of this repository, I'm not using this library in any of my projects anymore. But I'm always happy to facilitate users by reviewing, merging and releasing versions :)
